version: '3.8'
 
services: 
  db: 
    image: mysql:latest 
    container_name: dbregmex 
    restart: always 
    environment: 
      MYSQL_ROOT_PASSWORD: ema 
    volumes: 
      - ./db:/var/lib/mysql 
    ports: 
      - "3306:3306" 
    networks: 
      - dbregmexweb
 
  web: 
    image: php:8.1-apache 
    container_name: servidor_regmex 
    restart: always 
    volumes: 
      - ./RegistroUsuario:/var/www/html 
    ports: 
      - "9090:80" 
    depends_on: 
      - db 
    networks: 
      - dbregmexweb 
    command: >
      bash -c "docker-php-ext-install mysqli opcache && apache2-foreground"

networks: 
  dbregmexweb: 
    driver: bridge
